[package]
name = "markview"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "markview"
path = "src/main.rs"

[dependencies]
markdown-core = { path = "../markdown-core" }
memmap2 = "0.9"

[dependencies.objc2]
version = "0.6"

[dependencies.objc2-foundation]
version = "0.3"
features = [
    "NSString",
    "NSArray",
    "NSDictionary",
    "NSAttributedString",
    "NSNotification",
    "NSTimer",
    "NSRunLoop",
    "NSURL",
    "NSError",
    "NSGeometry",
    "NSObjCRuntime",
    "NSRange",
    "NSValue",
    "NSThread",
    "NSUserDefaults",
]

[dependencies.objc2-app-kit]
version = "0.3"
features = [
    "NSApplication",
    "NSResponder",
    "NSWindow",
    "NSView",
    "NSMenu",
    "NSMenuItem",
    "NSRunningApplication",
    "NSScreen",
    "NSEvent",
    "NSColor",
    "NSGraphics",
    "NSPasteboard",
    "NSTextField",
    "NSControl",
    "NSScrollView",
    "NSClipView",
    "NSFont",
    "NSFontDescriptor",
    "NSFontManager",
    "NSButton",
    "NSImage",
    "NSStackView",
    "NSLayoutConstraint",
    "NSLayoutAnchor",
    "NSOpenPanel",
    "NSSavePanel",
    "NSPanel",
    "NSTrackingArea",
    "NSCursor",
    "NSAttributedString",
    "NSStringDrawing",
    "NSParagraphStyle",
    "NSText",
    "NSTextView",
    "NSTextStorage",
    "NSTextContainer",
    "NSLayoutManager",
    "NSProgressIndicator",
]
